name: Create Release

on:
  push:
    branches: [ main ]

jobs:
  github-release:
    name: Upload to GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel pyinstaller
      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile MainFolder/test.py
      - name: Build project
        run: |
          python -m compileall .
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{github.run_number}}
          release_name: ${{github.run_number}}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes ""
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'