name: Create Release

on:
  push:
    branches: [ main ]

jobs:
  github-release:
    name: Upload to GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel pyinstaller
      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile MainFolder/test.py
      - name: Build project
        run: |
          python -m compileall .
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Binary in GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: main/main.py
          asset_name: main
          asset_content_type: application/octet-stream